name: Backend Tests

on:
  push:
    branches: ['**']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Build wrapper packages
        run: |
          for dir in packages/mongodb-wrapper-v*; do
            if [ -f "$dir/package.json" ]; then
              cd $dir
              npm ci
              npm run build || echo "No build script for $dir"
              cd -
            fi
          done

      - name: Verify repository structure
        run: |
          ls -la .
          ls -la packages
          ls -la packages/mongodb-wrapper-v6
          ls -la packages/mongodb-wrapper-v5
          ls -la packages/mongodb-wrapper-v4
          ls -la packages/mongodb-wrapper-v3
          cat packages/mongodb-wrapper-v6/package.json
          ls -la packages/mongodb-wrapper-v6/dist || echo "No dist directory for mongodb-wrapper-v6"

      - name: Install dependencies
        run: |
          cd backend
          npm ci
        env:
          CI: true

      - name: Verify node_modules
        run: |
          ls -la backend/node_modules/mongodb-wrapper-v6
          ls -la backend/node_modules/mongodb-wrapper-v5
          ls -la backend/node_modules/mongodb-wrapper-v4
          ls -la backend/node_modules/mongodb-wrapper-v3

      - name: Run tests
        run: |
          cd backend
          npm test
        env:
          CI: true

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: backend/coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
